// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_RMsxndqTXjsJ1jhb_PkeBchC74a1iWU',
    appId: '1:496349822788:web:a6bf88c862f3ee4c3a6111',
    messagingSenderId: '496349822788',
    projectId: 'elderhome-25df1',
    authDomain: 'elderhome-25df1.firebaseapp.com',
    storageBucket: 'elderhome-25df1.appspot.com',
    measurementId: 'G-V2E6WK4SY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8GSUpKaY5yx7-DQyQ4Rk4WpcTwJPjbW4',
    appId: '1:496349822788:android:73a2707676c9fb643a6111',
    messagingSenderId: '496349822788',
    projectId: 'elderhome-25df1',
    storageBucket: 'elderhome-25df1.appspot.com',
  );
}
